#Exercise A

In [9]:
# A. Creating an ndarray object (A) with values from 1 to 100 in a nested Python List
import numpy as np
A=np.array([1,2,3,4,5,6,7,8,9,10])



In [10]:
#Returns the dimensions of the array
A.shape

(10,)

In [11]:
#Returns the maximum value in the array, which is 10.
A.max()

10

In [12]:
#A numpy function that also returns the maximum value in the array
np.max(A)

10

#Exercise B

In [13]:
#Create a 5x5 integer-array filled with ones
B=np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])
B

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#Returns the shape of the array
B.shape

(5, 5)

In [15]:
#Returns the size of the array
B.size

25

In [16]:
# Returns the number of dimensions of the array, which is 2
B.ndim

2

#Exercise C

In [17]:
#Create an array of values from -5 to +5 and multiply each value with 2
C=np.arange(-5,5)*2
C

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

#Lesson 2.2

In [18]:
#The start value is 1 and the stop value is 30*2 since the incrementing value is 2
D=np.arange(1,2*30, 2)
D


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [19]:
#The resulting array will be multiplied its value by 3.
D=D*3
D

array([  3,   9,  15,  21,  27,  33,  39,  45,  51,  57,  63,  69,  75,
        81,  87,  93,  99, 105, 111, 117, 123, 129, 135, 141, 147, 153,
       159, 165, 171, 177])

In [5]:
#Exercise A.1
import numpy as np

# The start value is 1, the stop value is 1 + 2*30 (to get 30 values), and the step is 2
values = np.arange(1, 1 + 2*30, 2)

# The result is an array of 30 values starting from 1, incrementing by 2 each time

print(values)




[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]


In [6]:
#Exercise A.2

result = values * 3

# Print the result
print(result)

[  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


#Lesson 2

In [7]:
# A. Create a four dimensional array of random integers in the interval [0, 12]
# The array has a shape of (2, 3, 4, 5) as an example
import numpy as np


four_dim = np.random.randint(0, 13, (2, 3, 4, 5))
print("Four dimensional array:")
print(four_dim)

# Get the dimensions, shape, and size of the array
dimensions = four_dim.ndim
shape = four_dim.shape
size = four_dim.size

# The result is a 4D array with random integers between 0 and 12
# The dimensions, shape, and size provide information about the array structure
print("\nDimensions:", dimensions)
print("Shape:", shape)
print("Size:", size)

# B. Get the maximum number for each dimension
max_per_dimension = [np.max(four_dim, axis=i) for i in range(dimensions)]
print("\nMaximum number for each dimension:")
print(max_per_dimension)

# The result is an array containing the maximum values across each dimension

# C. Multiply each element in the array by 4
multiplied = four_dim * 4
print("\narray after multiplication by 4:")
print(multiplied)

# The result is a new 4D array where each element is the original value multiplied by 4



Four dimensional array:
[[[[ 0 12  8  9  6]
   [11  6 11 10  4]
   [ 7  5 12 12 10]
   [ 2  3  8 11  8]]

  [[ 4  0  4  1  7]
   [ 2  8  5 10  7]
   [ 7  9 12  4  0]
   [ 1  5  8  9  6]]

  [[ 8  6  5  8  4]
   [10  0  9  7 10]
   [ 7  9  9  8  7]
   [ 2 10  0  8 12]]]


 [[[12  3  3  8 10]
   [ 8  2  6  7  1]
   [ 9  4  0  4  0]
   [10  2  7  5 11]]

  [[ 0 12  7  0  4]
   [ 8  0  5  5  6]
   [10 10  8 12  0]
   [ 8  0  1  8  7]]

  [[ 0 12  2  4  1]
   [ 7  4  0  2  7]
   [ 1  6  2  8  5]
   [ 7  7  0  5 10]]]]

Dimensions: 4
Shape: (2, 3, 4, 5)
Size: 120

Maximum number for each dimension:
[array([[[12, 12,  8,  9, 10],
        [11,  6, 11, 10,  4],
        [ 9,  5, 12, 12, 10],
        [10,  3,  8, 11, 11]],

       [[ 4, 12,  7,  1,  7],
        [ 8,  8,  5, 10,  7],
        [10, 10, 12, 12,  0],
        [ 8,  5,  8,  9,  7]],

       [[ 8, 12,  5,  8,  4],
        [10,  4,  9,  7, 10],
        [ 7,  9,  9,  8,  7],
        [ 7, 10,  0,  8, 12]]]), array([[[ 8, 12,  8,  9,  7],
  